# Generated by Django 3.0.5 on 2020-05-01 17:45

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200501_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='average_score',
            field=models.FloatField(blank=True, null=TabError, validators=[classroom.models.validate_negative]),
        ),
    ]
